package com.senla.opekun.eqipmentrental.model.enums;

/**
 * @author Алексей Опекун
 * @version 1.0
 */
public enum ActionNames {
    REGISTRATION, CREATE_PRODUCT, CREATE_MANUFACTURER, CREATE_PRODUCT_CHARACTERISTIC, CREATE_CATEGORY, CREATE_CHARACTERISTIC, CHANGE_PRODUCT, CHANGE_PRODUCT_CHARACTERISTIC, CHANGE_CHARACTERISTIC, CHANGE_MANUFACTURER, CHANGE_USER_PERSON, CHANGE_CATEGORY, DELETE_PRODUCT, DELETE_PRODUCT_CHARACTERISTIC, DELETE_CHARACTERISTIC, DELETE_MANUFACTURER, DELETE_CATEGORY
}
