export const enInteface = {
  authorizaton: 'Authorizaton',
  signOut: 'Sign out',
  signIn: 'Sign in',
  registration: 'Registration',
  userProfile: 'Profile',
  categorys: 'Categorys',
  manufacturers: 'Manufacturers',
  characteristics: 'Characteristics',
  users: 'Users',
  products: 'Products',
  login: 'Login:',
  password: 'Password:',
  back: 'Back:',
  createUserProfile: 'Create user profile',
  firstName: 'First name',
  secondName: 'Second name',
  nickname: 'Nickname ',
  phoneNumber: 'Phone number',
  email: 'Email',
  save: 'Save',
  cansel: 'Cansel',
  createManufacturer: 'Create manufacturer',
  listManufacturers: 'List Manufacturers',
  name: 'Name',
  countryOfAssembly: 'Country of assembly',
  link: 'Link',
  update: 'Update',
  choose: 'Choose',
  editManufacturer: 'Edit manufacturer',
  createCategory: 'Create categoty',
  editCategory: 'Edit category',
  createCharacteristic: 'Create characteristic',
  editCharacteristic: 'Edit characteristic',
  productHistorys: 'Product historys',
  dateOfreceiving: 'Date of receiving',
  returnDate: 'Return date',
  rent: 'Rent',
  wrongDate: 'Wrong date',
  createProduct: 'Create product',
  price: 'Price',
  return: 'Return',
  next: 'Next',
  editProduct: 'Edit product',
  productCharacteristics: 'Product characteristics',
  createProductCharacteristic: 'Create product characteristic',
  value: 'Value',
  manufacturer: 'Manufacturer',
  addCharacteristic: 'Add characteristic',
  editProductCharacteristics: 'Edit product caharcteristic ',
  debtorUser: 'Debtor users',
  allUsers: 'All users',
  rolse: 'Roles',
  role: 'Role',
  editProfile: 'Edit user profile',
  userProducts: 'User products',
  welcom: ' Welcom to equipment rental',
  notSignInException: 'You are not sign in',
  createUserException: 'This login exist',
  createPersonException: 'This nickname exist',
  createEntityException: 'This name exist',
  signInException: 'Wrong login or password',
  emptyDataException: 'Please fill in all the fields',
  serverException: 'Server problems',
  userActions: 'User actions',
  date: 'Date',
  action: 'Action',
  entityId: 'Entity id',
};
