export const ruInteface = {
  authorizaton: 'Авторизация',
  signOut: 'Выход из системы',
  signIn: 'Вход в систему',
  registration: 'регистрация',
  userProfile: 'Профиль',
  categorys: 'Категории',
  manufacturers: 'Производители',
  characteristics: 'Характеристики',
  users: 'Пользователи',
  products: 'Оборудование',
  login: 'Логин:',
  password: 'Пароль:',
  back: 'Назад:',
  createUserProfile: 'Создание профиля',
  firstName: 'Имя',
  secondName: 'Фамилия',
  nickname: 'Никнейм ',
  phoneNumber: 'Телефонный номер',
  email: 'Почта',
  save: 'Сохранить',
  cansel: 'Отмена',
  createManufacturer: 'Созжание производителя',
  listManufacturers: 'Производители',
  name: 'Название',
  countryOfAssembly: 'Страна производитель',
  link: 'Ссылка',
  update: 'Изменить',
  choose: 'Выбрать',
  editManufacturer: 'Изменение производителся',
  createCategory: 'Создание категории',
  editCategory: 'Изменение категории',
  createCharacteristic: 'Создание характеристики',
  editCharacteristic: 'Изменение характеристики',
  productHistorys: 'История заказов оборудования',
  dateOfreceiving: 'Дата взятия в аренду',
  returnDate: 'Дата возвращения',
  rent: 'Арендовать',
  wrongDate: 'Не допустимое значение для даты',
  createProduct: 'Создание оборудования',
  price: 'Цена',
  return: 'Вернуть',
  next: 'Следующее',
  editProduct: 'Изменение продукта',
  productCharacteristics: 'Характеристики продукта',
  createProductCharacteristic: 'Создание характеристик продукта',
  value: 'Значение',
  manufacturer: 'Производитель',
  addCharacteristic: 'Добавать характеристику',
  editProductCharacteristics: 'Изменение характеристики продукта ',
  debtorUser: 'Должники ',
  allUsers: 'Все пользователи',
  rolse: 'Роли',
  role: 'Роль',
  editProfile: 'Изменение профиля',
  userProducts: 'Оборудование пользователя',
  welcom: ' Добро пожаловать в аренду оборудования',
  createUserException: 'Такой логин существует',
  notSignInException: 'Вы не зашли в систему',
  createPersonException: 'Такой никнейм существет',
  createEntityException: 'Такое название существет',
  signInException: 'Неверный логи или пароль',
  emptyDataException: 'Пожалуйста заполните все поля',
  serverException: 'Проблемы с сервером ',
  userActions: 'Активность пользователя',
  date: 'Дата',
  action: 'Действие',
  entityId: 'id изменяемого объекта',
};
